# Generated by Django 2.1.10 on 2019-07-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StomachacheSurvey',
            fields=[
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stomach', serialize=False, to='survey.SurveyMeta')),
                ('symptom_start', models.CharField(choices=[('less_than_month', '한 달이 안됐습니다.'), ('more_than_month', '한 달이 넘었습니다.')], max_length=50)),
                ('symptom_start_less_than_month', models.DateField(default='2019-07-23')),
                ('fast_or_slow', models.CharField(choices=[('fast', '갑자기'), ('slow', '천천히')], max_length=20)),
                ('symtpon_situation', models.CharField(max_length=50)),
                ('symtpom_location', models.CharField(choices=[('whole abdomen', '복부 전체'), ('sternal', '명치'), ('umbilicus', '배꼽'), ('flank', '옆구리'), ('LUQ', '왼쪽 위'), ('LLQ', '왼쪽 아래'), ('RUQ', '오른쪽 위'), ('RLQ', '오른쪽 아래')], default='NULL', max_length=20)),
                ('location_move', models.BooleanField(default=False)),
                ('location_move_how', models.CharField(max_length=100)),
                ('pain_spread', models.BooleanField(default=False)),
                ('pain_spread_where', models.CharField(max_length=100)),
                ('pain_duration', models.CharField(choices=[('lest_than_10m', '10분 미만'), ('from_10m_to_1h', '10분 ~ 1시간'), ('more_than_1h', '1시간 이상'), ('all_day', '하루종일')], max_length=20)),
                ('pain_repeated', models.BooleanField(default=False)),
                ('pain_per_day', models.CharField(choices=[('0_to_1', '0~1회'), ('2_to_3', '2~3회'), ('4_to_5', '4회~5회'), ('more_than_6', '6회이상')], max_length=20)),
                ('pain_worse', models.BooleanField(default=False)),
                ('pain_experience', models.BooleanField(default=False)),
                ('pain_character', models.CharField(choices=[('crushing', '쥐어짜듯'), ('burning', '타는듯'), ('stabbing', '베이듯'), ('splitting', '찢어지듯')], max_length=20)),
                ('pain_score', models.CharField(choices=[('1', '1점'), ('2', '2점'), ('3', '3점'), ('4', '4점'), ('5', '5점'), ('6', '6점'), ('7', '7점'), ('8', '8점'), ('9', '9점'), ('10', '10점')], max_length=20)),
                ('associated_symptom_digestive', models.CharField(choices=[('change of appetite', '식욕감소'), ('nausea', '구역질'), ('vomiting', '구토'), ('vomiting blood', '토혈'), ('abdominal inflation', '복부팽만'), ('lump on abdomen', '복부종괴'), ('constipation', '변비'), ('diarrhea', '설사'), ('rectal_bleeding', '혈변'), ('melena', '흑색변'), ('steatorrhea', '지방변'), ('jaundice', '황달'), ('nothing', '해당사항 없음')], max_length=20)),
                ('associated_symptom_circulatory', models.CharField(choices=[('chest pain', '가슴통증'), ('shortness of breah', '호흡곤란'), ('cough', '기침'), ('runny nose', '콧물'), ('nothing', '해당사항 없음')], max_length=20)),
                ('associated_symptom_gynecology', models.CharField(choices=[('colporrhagia', '질출혈'), ('leukorrhea', '질분비물'), ('menstrual cycle change', '생리주기변화'), ('pregnant possibility', '임신가능성'), ('nothing', '해당사항 없음')], max_length=20)),
                ('associated_symptom_whole_body', models.CharField(choices=[('fever', '발열'), ('chilling', '오한'), ('fatigue', '피로'), ('weight change', '체중변화'), ('sweating', '식은땀'), ('sleep disturbance', '수면곤란'), ('headache', '두통'), ('nothing', '해당사항 없음')], max_length=20)),
                ('associated_symptom_urinary', models.CharField(choices=[('painful urination', '배뇨통'), ('chnage the quantity of urine', '소변량변화'), ('red urine', '혈뇨'), ('foamy urine', '거품뇨'), ('frequency', '잦은 소변'), ('nothing', '해당사항 없음')], max_length=20)),
                ('associated_symptom_others', models.CharField(max_length=100)),
                ('factor', models.CharField(choices=[('after meal', '식사후 심해짐'), ('no meal', '공복에심해짐'), ('after alchol', '음주후 심해짐'), ('posture', '자세에따라 통증변화'), ('urination', '배뇨시 통증변화'), ('defecation', '배변시 통증변화'), ('nothing', '해당사항 없음')], max_length=20)),
                ('other_factor', models.CharField(max_length=100)),
                ('abdomen_relevant', models.CharField(choices=[('복부를 다친 적이 있음', '복부를 다친 적이 있음'), ('복부 수술을 받은 적이 있음', '복부 수술을 받은 적이 있음'), ('해당없음', '해당없음')], max_length=30)),
            ],
            bases=('survey.surveymeta',),
        ),
    ]
