# Generated by Django 2.1.10 on 2019-07-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveymeta_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stomachachesurvey',
            name='associated_symptom_circulatory',
            field=models.CharField(choices=[('chest pain', '가슴통증'), ('shortness of breah', '호흡곤란'), ('cough', '기침'), ('runny nose', '콧물')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stomachachesurvey',
            name='associated_symptom_digestive',
            field=models.CharField(choices=[('change of appetite', '식욕감소'), ('nausea', '구역질'), ('vomiting', '구토'), ('vomiting blood', '토혈'), ('abdominal inflation', '복부팽만'), ('lump on abdomen', '복부종괴'), ('constipation', '변비'), ('diarrhea', '설사'), ('rectal_bleeding', '혈변'), ('melena', '흑색변'), ('steatorrhea', '지방변'), ('jaundice', '황달')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stomachachesurvey',
            name='associated_symptom_gynecology',
            field=models.CharField(choices=[('colporrhagia', '질출혈'), ('leukorrhea', '질분비물'), ('menstrual cycle change', '생리주기변화'), ('pregnant possibility', '임신가능성')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stomachachesurvey',
            name='associated_symptom_urinary',
            field=models.CharField(choices=[('painful urination', '배뇨통'), ('chnage the quantity of urine', '소변량변화'), ('red urine', '혈뇨'), ('foamy urine', '거품뇨'), ('frequency', '잦은 소변')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stomachachesurvey',
            name='associated_symptom_whole_body',
            field=models.CharField(choices=[('fever', '발열'), ('chilling', '오한'), ('fatigue', '피로'), ('weight change', '체중변화'), ('sweating', '식은땀'), ('sleep disturbance', '수면곤란'), ('headache', '두통')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stomachachesurvey',
            name='factor',
            field=models.CharField(choices=[('after meal', '식사후 심해짐'), ('no meal', '공복에심해짐'), ('after alchol', '음주후 심해짐'), ('posture', '자세에따라 통증변화'), ('urination', '배뇨시 통증변화'), ('defecation', '배변시 통증변화')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stomachachesurvey',
            name='pain_character',
            field=models.CharField(choices=[('crushing', '쥐어짜듯'), ('burning', '타는듯'), ('stabbing', '베이듯'), ('splitting', '찢어지듯')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stomachachesurvey',
            name='symtpom_location',
            field=models.CharField(choices=[('whole abdomen', '통증'), ('sternal', '명치'), ('umbilicus', '배꼽'), ('flank', '옆구리'), ('LUQ', '왼쪽 위'), ('LLQ', '왼쪽 아래'), ('RUQ', '오른쪽 위'), ('RLQ', '오른쪽 아래')], default='NULL', max_length=20),
        ),
    ]
