# Generated by Django 2.1.7 on 2019-07-15 07:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], default='남성', max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.PositiveSmallIntegerField(default=160, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='이름', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
