# Generated by Django 2.1.7 on 2019-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190715_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='how_much_alchol',
            field=models.CharField(default='1주일에 한번', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='how_much_game',
            field=models.CharField(default='1주일에 한번', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='how_much_smoke',
            field=models.CharField(default='1주일에 한번', max_length=100),
        ),
    ]
