# Generated by Django 2.1.10 on 2019-07-22 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190722_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.PositiveSmallIntegerField(default=160, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='이름', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
