# Generated by Django 2.1.7 on 2019-07-21 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190721_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
